title: Aishwarya Sundaresan
description: Computational Biologist — Portfolio
url: "https://a-sundaresan.github.io"
baseurl: ""

theme: minima

author:
  name: Aishwarya Sundaresan
  email: asundaresan@proton.me
  github: a-sundaresan
  linkedin: a-sundaresan

markdown: kramdown
permalink: pretty
